const categoryMap = {
    'Ml-xxxx-lx': {letter: '', color: '#BD06D0', category: 'Ml-xxxx-lx', building: 'Mall', positioning: 'Luxury', special: '', construction: '', construction_eng: '', name: '奢华购物中心', name_eng: 'Luxury Mall'},
    'Ml-xxxx-pr': {letter: '', color: '#F740AF', category: 'Ml-xxxx-pr', building: 'Mall', positioning: 'Premium', special: '', construction: '', construction_eng: '', name: '高端购物中心', name_eng: 'Premium Mall'},
    'Ml-xxxx-br': {letter: '', color: '#FF0000', category: 'Ml-xxxx-br', building: 'Mall', positioning: 'Brand', special: '', construction: '', construction_eng: '', name: '品牌购物中心', name_eng: 'Brand Mall'},
    'Ml-xxxx-vl': {letter: '', color: '#008000', category: 'Ml-xxxx-vl', building: 'Mall', positioning: 'Value', special: '', construction: '', construction_eng: '', name: '平价购物中心', name_eng: 'Value Mall'},
    'Ml-xxxx-lc': {letter: '', color: '#00b300', category: 'Ml-xxxx-lc', building: 'Mall', positioning: 'Local', special: '', construction: '', construction_eng: '', name: '个体购物中心', name_eng: 'Local Mall'},
    'Ml-xxxx-fb': {letter: "B", color: '#B69FAF', category: 'Ml-xxxx-fb', building: 'Mall', positioning: '', special: 'Fashion Boutique', construction: '', construction_eng: '', name: '精品服装购物中心', name_eng: 'Fashion Boutique Mall'},
    'Ml-xxxx-mb': {letter: "B", color: '#B69FAF', category: 'Ml-xxxx-mb', building: 'Mall', positioning: '', special: 'Market Boutique', construction: '', construction_eng: '', name: '精品集市购物中心', name_eng: 'Market Boutique Mall'},
    'Ml-xxxx-po': {letter: "O", color: '#F740AF', category: 'Ml-xxxx-po', building: 'Mall', positioning: 'Premium', special: 'Outlet', construction: '', construction_eng: '', name: '高端奥特莱斯购物中心', name_eng: 'Premium Outlet Mall'},
    'Ml-xxxx-bo': {letter: "O", color: '#FF0000', category: 'Ml-xxxx-bo', building: 'Mall', positioning: 'Brand', special: 'Outlet', construction: '', construction_eng: '', name: '品牌奥特莱斯购物中心', name_eng: 'Brand Outlet Mall'},
    'Ml-xxxx-vo': {letter: "O", color: '#008000', category: 'Ml-xxxx-vo', building: 'Mall', positioning: 'Value', special: 'Outlet', construction: '', construction_eng: '', name: '平价奥特莱斯购物中心', name_eng: 'Value Outlet Mall'},
    'Ml-xxxx-pc': {letter: "F", color: '#F740AF', category: 'Ml-xxxx-pc', building: 'Mall', positioning: 'Premium', special: 'Food & Beverage', construction: '', construction_eng: '', name: '高端餐饮购物中心', name_eng: 'Premium F&B Mall'},
    'Ml-xxxx-bc': {letter: "F", color: '#FF0000', category: 'Ml-xxxx-bc', building: 'Mall', positioning: 'Brand', special: 'Food & Beverage', construction: '', construction_eng: '', name: '品牌餐饮购物中心', name_eng: 'Brand F&B Mall'},
    'Ml-xxxx-oc': {letter: "F", color: '#00b300', category: 'Ml-xxxx-oc', building: 'Mall', positioning: 'Local', special: 'Food & Beverage', construction: '', construction_eng: '', name: '个体餐饮购物中心', name_eng: 'Local F&B Mall'},
    'Ml-0003-fu': {letter: '', color: '#000079', category: 'Ml-0003-fu', building: 'Mall', positioning: '', special: '', construction: '即将开业', construction_eng: 'Opening', name: '购物中心-即将开业', name_eng: 'Mall - Future Opening'},
    'Ml-0012-fu': {letter: '', color: '#0000FF', category: 'Ml-0012-fu', building: 'Mall', positioning: '', special: '', construction: '未来12个月内开业', construction_eng: 'Less than 12 months', name: '购物中心-未来12个月内开业', name_eng: 'Mall - Future Open less than 12M'},
    'Ml-0024-fu': {letter: '', color: '#2894FF', category: 'Ml-0024-fu', building: 'Mall', positioning: '', special: '', construction: '未来12-24个月内开业', construction_eng: 'Between 12 - 24 months', name: '购物中心-未来12-24个月内开业', name_eng: 'Mall - Future Open between 12 - 24M'},
    'Ml-0025-fu': {letter: "+", color: '#2894FF', category: 'Ml-0025-fu', building: 'Mall', positioning: '', special: '', construction: '超过24个月后开业', construction_eng: 'More than 24 months', name: '购物中心-超过24个月后开业', name_eng: 'Mall - Future Open more than 24M'},
    'Ml-0001-fu': {letter: "P", color: '#2894FF', category: 'Ml-0001-fu', building: 'Mall', positioning: '', special: '', construction: '刚规划', construction_eng: 'Proposed', name: '购物中心-刚规划', name_eng: 'Mall - Future Proposed'},
    'Ml-xxxx-fu': {letter: "-", color: '#2894FF', category: 'Ml-xxxx-fu', building: 'Mall', positioning: '', special: '', construction: '不确定开业时间', construction_eng: 'Unknown', name: '购物中心-未开业-不确定开业时间', name_eng: 'Mall - Future'},
    'Ml-ss03-fu': {letter: "S", color: '#000079', category: 'Ml-ss03-fu', building: 'Mall', positioning: '', special: '', construction: '已停工-完成90%', construction_eng: 'Seems stopped-90% Finished', name: '购物中心-已停工-完成90%', name_eng: 'Mall - Future Seems stopped-90% Finished'},
    'Ml-ss12-fu': {letter: "S", color: '#0000FF', category: 'Ml-ss12-fu', building: 'Mall', positioning: '', special: '', construction: '已停工-完成70%', construction_eng: 'Seems stopped-70% Finished', name: '购物中心-已停工-完成70%', name_eng: 'Mall - Future Seems stopped-70% Finished'},
    'Ml-ss24-fu': {letter: "S", color: '#2894FF', category: 'Ml-ss24-fu', building: 'Mall', positioning: '', special: '', construction: '已停工-完成50%', construction_eng: 'Seems stopped-50% Finished', name: '购物中心-已停工-完成50%', name_eng: 'Mall - Future Seems stopped-50% Finished'},
    'Ml-ss25-fu': {letter: "S", color: '#2894FF', category: 'Ml-ss25-fu', building: 'Mall', positioning: '', special: '', construction: '已停工-完成10%', construction_eng: 'Seems stopped-10% Finished', name: '购物中心-已停工-完成10%', name_eng: 'Mall - Future Seems stopped-10% Finished'},
    'Ml-xxxx-pl': {letter: "L", color: '#F740AF', category: 'Ml-xxxx-pl', building: 'Mall', positioning: 'Premium', special: 'Lifestyle', construction: '', construction_eng: '', name: '高端生活方式购物中心', name_eng: 'Premium Lifestyle Mall'},
    'Ml-xxxx-ls': {letter: "L", color: '#FF0000', category: 'Ml-xxxx-ls', building: 'Mall', positioning: 'Brand', special: 'Lifestyle', construction: '', construction_eng: '', name: '生活方式购物中心', name_eng: 'Lifestyle Mall'},
    'Ml-xxxx-yo': {letter: "Y", color: '#B69FAF', category: 'Ml-xxxx-yo', building: 'Mall', positioning: '', special: 'Youth', construction: '', construction_eng: '', name: '青少年购物中心', name_eng: 'Youth Mall'},
    'Ml-xxxx-et': {letter: "E", color: '#B69FAF', category: 'Ml-xxxx-et', building: 'Mall', positioning: '', special: 'Entertainment', construction: '', construction_eng: '', name: '娱乐购物中心', name_eng: 'Entertainment Mall'},
    'Ml-xxxx-sr': {letter: "R", color: '#B69FAF', category: 'Ml-xxxx-sr', building: 'Mall', positioning: '', special: 'Services', construction: '', construction_eng: '', name: '服务购物中心', name_eng: 'Services Mall'},
    'Ml-xxxx-ct': {letter: "C", color: '#B69FAF', category: 'Ml-xxxx-ct', building: 'Mall', positioning: '', special: 'Convenience', construction: '', construction_eng: '', name: '便捷购物中心', name_eng: 'Convenience Mall'},
    'Ml-xxxx-fn': {letter: '', color: '#B69FAF', category: 'Ml-xxxx-fn', building: 'Mall', positioning: '', special: 'Furniture', construction: '', construction_eng: '', name: '家私购物中心', name_eng: 'Furniture Mall'},
    'Ml-xxxx-kd': {letter: '', color: '#B69FAF', category: 'Ml-xxxx-kd', building: 'Mall', positioning: '', special: 'Children', construction: '', construction_eng: '', name: '婴童购物中心', name_eng: 'Children Mall'},
    'Ml-xxxx-el': {letter: '', color: '#B69FAF', category: 'Ml-xxxx-el', building: 'Mall', positioning: '', special: 'Electronic', construction: '', construction_eng: '', name: '电子购物中心', name_eng: 'Electronic Mall'},
    'Ml-xxxx-jr': {letter: '', color: '#B69FAF', category: 'Ml-xxxx-jr', building: 'Mall', positioning: '', special: 'Jewelry', construction: '', construction_eng: '', name: '珠宝购物中心', name_eng: 'Jewelry Mall'},
    'Dp-xxxx-lx': {letter: '', color: '#BD06D0', category: 'Dp-xxxx-lx', building: 'Department Store', positioning: 'Luxury', special: '', construction: '', construction_eng: '', name: '奢华百货', name_eng: 'Luxury Department Store'},
    'Dp-xxxx-pr': {letter: '', color: '#F740AF', category: 'Dp-xxxx-pr', building: 'Department Store', positioning: 'Premium', special: '', construction: '', construction_eng: '', name: '高端百货', name_eng: 'Premium Department Store'},
    'Dp-xxxx-br': {letter: '', color: '#FF0000', category: 'Dp-xxxx-br', building: 'Department Store', positioning: 'Brand', special: '', construction: '', construction_eng: '', name: '品牌百货', name_eng: 'Brand Department Store'},
    'Dp-xxxx-vl': {letter: '', color: '#008000', category: 'Dp-xxxx-vl', building: 'Department Store', positioning: 'Value', special: '', construction: '', construction_eng: '', name: '平价百货', name_eng: 'Value Department Store'},
    'Dp-xxxx-lc': {letter: '', color: '#00b300', category: 'Dp-xxxx-lc', building: 'Department Store', positioning: 'Local', special: '', construction: '', construction_eng: '', name: '个体百货', name_eng: 'Local Department Store'},
    'Dp-xxxx-po': {letter: "O", color: '#F740AF', category: 'Dp-xxxx-po', building: 'Department Store', positioning: 'Premium', special: 'Outlet', construction: '', construction_eng: '', name: '高端奥特莱百货', name_eng: 'Premium Outlet Department Store'},
    'Dp-xxxx-bo': {letter: "O", color: '#FF0000', category: 'Dp-xxxx-bo', building: 'Department Store', positioning: 'Brand', special: 'Outlet', construction: '', construction_eng: '', name: '品牌奥特莱斯百货', name_eng: 'Brand Outlet Department Store'},
    'Dp-xxxx-vo': {letter: "O", color: '#008000', category: 'Dp-xxxx-vo', building: 'Department Store', positioning: 'Value', special: 'Outlet', construction: '', construction_eng: '', name: '平价奥特莱斯百货', name_eng: 'Value Outlet Department Store'},
    'Dp-0003-fu': {letter: '', color: '#000079', category: 'Dp-0003-fu', building: 'Department Store', positioning: '', special: '', construction: '即将开业', construction_eng: 'Opening', name: '百货-即将开业', name_eng: 'Department Store - Future Opening'},
    'Dp-0012-fu': {letter: '', color: '#0000FF', category: 'Dp-0012-fu', building: 'Department Store', positioning: '', special: '', construction: '未来12个月内开业', construction_eng: 'Less than 12 months', name: '百货-未来12个月内开业', name_eng: 'Department Store - Future Open less than 12M'},
    'Dp-0024-fu': {letter: '', color: '#2894FF', category: 'Dp-0024-fu', building: 'Department Store', positioning: '', special: '', construction: '未来12-24个月内开业', construction_eng: 'Between 12 - 24 months', name: '百货-未来12-24个月内开业', name_eng: 'Department Store - Future Open between 12 - 24M'},
    'Dp-0025-fu': {letter: "+", color: '#2894FF', category: 'Dp-0025-fu', building: 'Department Store', positioning: '', special: '', construction: '超过24个月后开业', construction_eng: 'More than 24 months', name: '百货-超过24个月后开业', name_eng: 'Department Store - Future Open more than 24M'},
    'Dp-0001-fu': {letter: "P", color: '#2894FF', category: 'Dp-0001-fu', building: 'Department Store', positioning: '', special: '', construction: '刚规划', construction_eng: 'Proposed', name: '百货-刚规划', name_eng: 'Department Store - Future Proposed'},
    'Dp-xxxx-fu': {letter: "-", color: '#2894FF', category: 'Dp-xxxx-fu', building: 'Department Store', positioning: '', special: '', construction: '不确定开业时间', construction_eng: 'Unknown', name: '百货-未开业-不确定开业时间', name_eng: 'Department Store - Future'},
    'Dp-ss03-fu': {letter: "S", color: '#000079', category: 'Dp-ss03-fu', building: 'Department Store', positioning: '', special: '', construction: '已停工-完成90%', construction_eng: 'Seems stopped-90% Finished', name: '百货-已停工-完成90%', name_eng: 'Department Store - Future Seems stopped-90% Finished'},
    'Dp-ss12-fu': {letter: "S", color: '#0000FF', category: 'Dp-ss12-fu', building: 'Department Store', positioning: '', special: '', construction: '已停工-完成70%', construction_eng: 'Seems stopped-70% Finished', name: '百货-已停工-完成70%', name_eng: 'Department Store - Future Seems stopped-70% Finished'},
    'Dp-ss24-fu': {letter: "S", color: '#2894FF', category: 'Dp-ss24-fu', building: 'Department Store', positioning: '', special: '', construction: '已停工-完成50%', construction_eng: 'Seems stopped-50% Finished', name: '百货-已停工-完成50%', name_eng: 'Department Store - Future Seems stopped-50% Finished'},
    'Dp-ss25-fu': {letter: "S", color: '#2894FF', category: 'Dp-ss25-fu', building: 'Department Store', positioning: '', special: '', construction: '已停工-完成10%', construction_eng: 'Seems stopped-10% Finished', name: '百货-已停工-完成10%', name_eng: 'Department Store - Future Seems stopped-10% Finished'},
    'Hy-xxxx-br': {letter: '', color: '#FF0000', category: 'Hy-xxxx-br', building: 'Hypermarket', positioning: 'Brand', special: '', construction: '', construction_eng: '', name: '品牌大卖场', name_eng: 'Brand Hypermarket'},
    'Hy-xxxx-vl': {letter: '', color: '#008000', category: 'Hy-xxxx-vl', building: 'Hypermarket', positioning: 'Value', special: '', construction: '', construction_eng: '', name: '平价大卖场', name_eng: 'Value Hypermarket'},
    'Hy-xxxx-lc': {letter: '', color: '#00b300', category: 'Hy-xxxx-lc', building: 'Hypermarket', positioning: 'Local', special: '', construction: '', construction_eng: '', name: '个体大卖场', name_eng: 'Local Hypermarket'},
    'Hy-xxxx-bo': {letter: "O", color: '#FF0000', category: 'Hy-xxxx-bo', building: 'Hypermarket', positioning: 'Brand', special: 'Outlet', construction: '', construction_eng: '', name: '品牌奥特莱斯大卖场', name_eng: 'Brand Outlet Hypermarket'},
    'Hy-xxxx-vo': {letter: "O", color: '#008000', category: 'Hy-xxxx-vo', building: 'Hypermarket', positioning: 'Value', special: 'Outlet', construction: '', construction_eng: '', name: '平价奥特莱斯大卖场', name_eng: 'Value Outlet Hypermarket'},
    'Hy-xxxx-gl': {letter: "G", color: '#FF0000', category: 'Hy-xxxx-gl', building: 'Hypermarket', positioning: 'Brand', special: 'Gallery', construction: '', construction_eng: '', name: '单店大卖场', name_eng: 'Gallery Hypermarket'},
    'Hy-xxxx-is': {letter: "I", color: '#00b300', category: 'Hy-xxxx-is', building: 'Hypermarket', positioning: 'Local', special: 'Individual Store', construction: '', construction_eng: '', name: '个体商户大卖场', name_eng: 'Individual Store Hypermarket'},
    'Hy-0012-fu': {letter: '', color: '#0000FF', category: 'Hy-0012-fu', building: 'Hypermarket', positioning: '', special: '', construction: '未来12个月内开业', construction_eng: 'Less than 12 months', name: '大卖场-未来12个月内开业', name_eng: 'Hypermarket - Future Open less than 12M'},
    'Hy-0013-fu': {letter: "+", color: '#2894FF', category: 'Hy-0013-fu', building: 'Hypermarket', positioning: '', special: '', construction: '超过12个月后开业', construction_eng: 'More than 12 months', name: '大卖场-超过12个月后开业', name_eng: 'Hypermarket - Future Open More than 12M'},
    'Hy-ss12-fu': {letter: "S", color: '#0000FF', category: 'Hy-ss12-fu', building: 'Hypermarket', positioning: '', special: '', construction: '已停工-完成70%', construction_eng: 'Seems stopped-70% Finished', name: '大卖场-已停工-完成70%', name_eng: 'Hypermarket - Future Seems stopped-70% Finished'},
    'Hy-ss13-fu': {letter: "S", color: '#2894FF', category: 'Hy-ss13-fu', building: 'Hypermarket', positioning: '', special: '', construction: '已停工-完成30%', construction_eng: 'Seems stopped-30% Finished', name: '大卖场-已停工-完成30%', name_eng: 'Hypermarket - Future Seems stopped-30% Finished'},
    'RB-xxxx-lx': {letter: '', color: '#BD06D0', category: 'RB-xxxx-lx', building: 'Retail Building', positioning: 'Luxury', special: '', construction: '', construction_eng: '', name: '奢华商业大楼', name_eng: 'Luxury Retail Building'},
    'RB-xxxx-br': {letter: '', color: '#FF0000', category: 'RB-xxxx-br', building: 'Retail Building', positioning: 'Brand', special: '', construction: '', construction_eng: '', name: '品牌商业大楼', name_eng: 'Brand Retail Building'},
    'RB-xxxx-rs': {letter: '', color: '#00b300', category: 'RB-xxxx-rs', building: 'Retail Building', positioning: 'Local', special: '', construction: '', construction_eng: '', name: '商铺商业大楼', name_eng: 'Retail Space Retail Building'},
    'RB-xxxx-pc': {letter: "F", color: '#F740AF', category: 'RB-xxxx-pc', building: 'Retail Building', positioning: 'Premium', special: 'Food & Beverage', construction: '', construction_eng: '', name: '高端餐饮商业大楼', name_eng: 'Premium F&B (Catering) Retail Building'},
    'RB-xxxx-bc': {letter: "F", color: '#FF0000', category: 'RB-xxxx-bc', building: 'Retail Building', positioning: 'Brand', special: 'Food & Beverage', construction: '', construction_eng: '', name: '品牌餐饮商业大楼', name_eng: 'Brand F&B (Catering) Retail Building'},
    'RB-xxxx-oc': {letter: "F", color: '#00b300', category: 'RB-xxxx-oc', building: 'Retail Building', positioning: 'Local', special: 'Food & Beverage', construction: '', construction_eng: '', name: '个体餐饮商业大楼', name_eng: 'Local F&B (Catering) Retail Building'},
    'RB-0003-fu': {letter: '', color: '#000079', category: 'RB-0003-fu', building: 'Retail Building', positioning: '', special: '', construction: '即将开业', construction_eng: 'Opening', name: '商业大楼-即将开业', name_eng: 'Retail Building - Future Opening'},
    'RB-xxxx-fu': {letter: "-", color: '#2894FF', category: 'RB-xxxx-fu', building: 'Retail Building', positioning: '', special: '', construction: '不确定开业时间', construction_eng: 'Unknown', name: '商业大楼-未开业-不确定开业时间', name_eng: 'Retail Building - Future'},
    'RB-ss12-fu': {letter: "S", color: '#0000FF', category: 'RB-ss12-fu', building: 'Retail Building', positioning: '', special: '', construction: '已停工-完成70%', construction_eng: 'Seems stopped-70% Finished', name: '商业大楼-已停工-完成70%', name_eng: 'Retail Building - Future Seems stopped-70% Finished'},
    'RB-ss13-fu': {letter: "S", color: '#2894FF', category: 'RB-ss13-fu', building: 'Retail Building', positioning: '', special: '', construction: '已停工-完成30%', construction_eng: 'Seems stopped-30% Finished', name: '商业大楼-已停工-完成30%', name_eng: 'Retail Building - Future Seems stopped-30% Finished'},
    'RB-xxxx-fb': {letter: "B", color: '#B69FAF', category: 'RB-xxxx-fb', building: 'Retail Building', positioning: '', special: 'Fashion Boutique', construction: '', construction_eng: '', name: '精品服装商业大楼', name_eng: 'Fashion Boutique Retail Building'},
    'RB-xxxx-mb': {letter: "B", color: '#B69FAF', category: 'RB-xxxx-mb', building: 'Retail Building', positioning: '', special: 'Market Boutique', construction: '', construction_eng: '', name: '精品集市商业大楼', name_eng: 'Market Boutique Retail Building'},
    'RB-xxxx-yo': {letter: "Y", color: '#B69FAF', category: 'RB-xxxx-yo', building: 'Retail Building', positioning: '', special: 'Youth', construction: '', construction_eng: '', name: '青少年商业大楼', name_eng: 'Youth Retail Building'},
    'RB-xxxx-et': {letter: "E", color: '#B69FAF', category: 'RB-xxxx-et', building: 'Retail Building', positioning: '', special: 'Entertainment', construction: '', construction_eng: '', name: '娱乐商业大楼', name_eng: 'Entertainment Retail Building'},
    'RB-xxxx-sr': {letter: "R", color: '#B69FAF', category: 'RB-xxxx-sr', building: 'Retail Building', positioning: '', special: 'Services', construction: '', construction_eng: '', name: '服务商业大楼', name_eng: 'Services Retail Building'},
    'RB-xxxx-ct': {letter: "C", color: '#B69FAF', category: 'RB-xxxx-ct', building: 'Retail Building', positioning: '', special: 'Convenience', construction: '', construction_eng: '', name: '便捷商业大楼', name_eng: 'Convenience Retail Building'},
    'RB-xxxx-fn': {letter: '', color: '#B69FAF', category: 'RB-xxxx-fn', building: 'Retail Building', positioning: '', special: 'Furniture', construction: '', construction_eng: '', name: '家私商业大楼', name_eng: 'Furniture Retail Building'},
    'RB-xxxx-kd': {letter: '', color: '#B69FAF', category: 'RB-xxxx-kd', building: 'Retail Building', positioning: '', special: 'Children', construction: '', construction_eng: '', name: '婴童商业大楼', name_eng: 'Children Retail Building'},
    'RB-xxxx-el': {letter: '', color: '#B69FAF', category: 'RB-xxxx-el', building: 'Retail Building', positioning: '', special: 'Electronic', construction: '', construction_eng: '', name: '电子商业大楼', name_eng: 'Electronic Retail Building'},
    'RB-xxxx-jr': {letter: '', color: '#B69FAF', category: 'RB-xxxx-jr', building: 'Retail Building', positioning: '', special: 'Jewelry', construction: '', construction_eng: '', name: '珠宝商业大楼', name_eng: 'Jewelry Retail Building'},
    'OB-xxxx-lx': {letter: '', color: '#BD06D0', category: 'OB-xxxx-lx', building: 'Office Building', positioning: 'Luxury', special: '', construction: '', construction_eng: '', name: '奢华写字楼商业大楼', name_eng: 'Luxury Office Building'},
    'OB-xxxx-br': {letter: '', color: '#FF0000', category: 'OB-xxxx-br', building: 'Office Building', positioning: 'Brand', special: '', construction: '', construction_eng: '', name: '品牌写字楼商业大楼', name_eng: 'Brand Office Building'},
    'OB-xxxx-rs': {letter: '', color: '#00b300', category: 'OB-xxxx-rs', building: 'Office Building', positioning: 'Local', special: '', construction: '', construction_eng: '', name: '商铺写字楼商业大楼', name_eng: 'Retail Space Office Building'},
    'OB-xxxx-pc': {letter: "F", color: '#F740AF', category: 'OB-xxxx-pc', building: 'Office Building', positioning: 'Premium', special: 'Food & Beverage', construction: '', construction_eng: '', name: '高端餐饮写字楼商业大楼', name_eng: 'Premium F&B Office Building'},
    'OB-xxxx-bc': {letter: "F", color: '#FF0000', category: 'OB-xxxx-bc', building: 'Office Building', positioning: 'Brand', special: 'Food & Beverage', construction: '', construction_eng: '', name: '品牌餐饮写字楼商业大楼', name_eng: 'Brand F&B Office Building'},
    'OB-xxxx-oc': {letter: "F", color: '#00b300', category: 'OB-xxxx-oc', building: 'Office Building', positioning: 'Local', special: 'Food & Beverage', construction: '', construction_eng: '', name: '个体餐饮写字楼商业大楼', name_eng: 'Local F&B Office Building'},
    'OB-0003-fu': {letter: '', color: '#000079', category: 'OB-0003-fu', building: 'Office Building', positioning: '', special: '', construction: '即将开业', construction_eng: 'Opening', name: '写字楼商业大楼-即将开业', name_eng: 'Office Building - Future Opening'},
    'OB-xxxx-fu': {letter: "-", color: '#2894FF', category: 'OB-xxxx-fu', building: 'Office Building', positioning: '', special: '', construction: '不确定开业时间', construction_eng: 'Unknown', name: '写字楼商业大楼-未开业-不确定开业时间', name_eng: 'Office Building - Future'},
    'OB-ss12-fu': {letter: "S", color: '#0000FF', category: 'OB-ss12-fu', building: 'Office Building', positioning: '', special: '', construction: '已停工-完成70%', construction_eng: 'Seems stopped-70% Finished', name: '写字楼商业大楼-已停工-完成70%', name_eng: 'Office Building - Future Seems stopped-70% Finished'},
    'OB-ss13-fu': {letter: "S", color: '#2894FF', category: 'OB-ss13-fu', building: 'Office Building', positioning: '', special: '', construction: '已停工-完成30%', construction_eng: 'Seems stopped-30% Finished', name: '写字楼商业大楼-已停工-完成30%', name_eng: 'Office Building - Future Seems stopped-30% Finished'},
    'OB-xxxx-cf': {letter: '', color: '#B69FAF', category: 'OB-xxxx-cf', building: 'Office Building', positioning: '', special: 'Conference Center', construction: '', construction_eng: '', name: '会议中心', name_eng: 'Conference Center'},
    'AB-xxxx-lx': {letter: '', color: '#BD06D0', category: 'AB-xxxx-lx', building: 'Apartment Building', positioning: 'Luxury', special: '', construction: '', construction_eng: '', name: '奢华住宅商业大楼', name_eng: 'Luxury Apartment Building'},
    'AB-xxxx-br': {letter: '', color: '#FF0000', category: 'AB-xxxx-br', building: 'Apartment Building', positioning: 'Brand', special: '', construction: '', construction_eng: '', name: '品牌住宅商业大楼', name_eng: 'Brand Apartment Building'},
    'AB-xxxx-rs': {letter: '', color: '#00b300', category: 'AB-xxxx-rs', building: 'Apartment Building', positioning: 'Local', special: '', construction: '', construction_eng: '', name: '商铺住宅商业大楼', name_eng: 'Retail Space Apartment Building'},
    'AB-xxxx-pc': {letter: "F", color: '#F740AF', category: 'AB-xxxx-pc', building: 'Apartment Building', positioning: 'Premium', special: 'Food & Beverage', construction: '', construction_eng: '', name: '高端餐饮住宅商业大楼', name_eng: 'Premium F&B Apartment Building'},
    'AB-xxxx-bc': {letter: "F", color: '#FF0000', category: 'AB-xxxx-bc', building: 'Apartment Building', positioning: 'Brand', special: 'Food & Beverage', construction: '', construction_eng: '', name: '品牌餐饮住宅商业大楼', name_eng: 'Brand F&B Apartment Building'},
    'AB-xxxx-oc': {letter: "F", color: '#00b300', category: 'AB-xxxx-oc', building: 'Apartment Building', positioning: 'Local', special: 'Food & Beverage', construction: '', construction_eng: '', name: '个体餐饮住宅商业大楼', name_eng: 'Local F&B Apartment Building'},
    'AB-0003-fu': {letter: '', color: '#000079', category: 'AB-0003-fu', building: 'Apartment Building', positioning: '', special: '', construction: '即将开业', construction_eng: 'Opening', name: '住宅商业大楼-即将开业', name_eng: 'Apartment Building - Future Opening'},
    'AB-xxxx-fu': {letter: "-", color: '#2894FF', category: 'AB-xxxx-fu', building: 'Apartment Building', positioning: '', special: '', construction: '不确定开业时间', construction_eng: 'Unknown', name: '住宅商业大楼-未开业-不确定开业时间', name_eng: 'Apartment Building - Future'},
    'AB-ss12-fu': {letter: "S", color: '#0000FF', category: 'AB-ss12-fu', building: 'Apartment Building', positioning: '', special: '', construction: '已停工-完成70%', construction_eng: 'Seems stopped-70% Finished', name: '住宅商业大楼-已停工-完成70%', name_eng: 'Apartment Building - Future Seems stopped-70% Finished'},
    'AB-ss13-fu': {letter: "S", color: '#2894FF', category: 'AB-ss13-fu', building: 'Apartment Building', positioning: '', special: '', construction: '已停工-完成30%', construction_eng: 'Seems stopped-30% Finished', name: '住宅商业大楼-已停工-完成30%', name_eng: 'Apartment Building - Future Seems stopped-30% Finished'},
    'HB-xxxx-lx': {letter: '', color: '#BD06D0', category: 'HB-xxxx-lx', building: 'Hotel Building', positioning: 'Luxury', special: '', construction: '', construction_eng: '', name: '奢华酒店商业大楼', name_eng: 'Luxury Hotel Building'},
    'HB-xxxx-br': {letter: '', color: '#FF0000', category: 'HB-xxxx-br', building: 'Hotel Building', positioning: 'Brand', special: '', construction: '', construction_eng: '', name: '品牌酒店商业大楼', name_eng: 'Brand Hotel Building'},
    'HB-xxxx-rs': {letter: '', color: '#00b300', category: 'HB-xxxx-rs', building: 'Hotel Building', positioning: 'Local', special: '', construction: '', construction_eng: '', name: '商铺酒店商业大楼', name_eng: 'Retail Space Hotel Building'},
    'HB-0003-fu': {letter: '', color: '#000079', category: 'HB-0003-fu', building: 'Hotel Building', positioning: '', special: '', construction: '即将开业', construction_eng: 'Opening', name: '酒店商业大楼-即将开业', name_eng: 'Hotel Building - Future Opening'},
    'HB-xxxx-fu': {letter: "-", color: '#2894FF', category: 'HB-xxxx-fu', building: 'Hotel Building', positioning: '', special: '', construction: '不确定开业时间', construction_eng: 'Unknown', name: '酒店商业大楼-未开业-不确定开业时间', name_eng: 'Hotel Building - Future'},
    'HB-ss12-fu': {letter: "S", color: '#0000FF', category: 'HB-ss12-fu', building: 'Hotel Building', positioning: '', special: '', construction: '已停工-完成70%', construction_eng: 'Seems stopped-70% Finished', name: '酒店商业大楼-已停工-完成70%', name_eng: 'Hotel Building - Future Seems stopped-70% Finished'},
    'HB-ss13-fu': {letter: "S", color: '#2894FF', category: 'HB-ss13-fu', building: 'Hotel Building', positioning: '', special: '', construction: '已停工-完成30%', construction_eng: 'Seems stopped-30% Finished', name: '酒店商业大楼-已停工-完成30%', name_eng: 'Hotel Building - Future Seems stopped-30% Finished'},
    'Ai-xxxx-yy': {letter: '', color: '#B69FAF', category: 'Ai-xxxx-yy', building: 'Interest Point', positioning: '', special: 'Airport', construction: '', construction_eng: '', name: '机场兴趣点', name_eng: 'Airport Interest Point'},
    'Tr-xxxx-yy': {letter: '', color: '#B69FAF', category: 'Tr-xxxx-yy', building: 'Interest Point', positioning: '', special: 'Train Station', construction: '', construction_eng: '', name: '火车站兴趣点', name_eng: 'Train Station Interest Point'},
    'Sb-xxxx-yy': {letter: '', color: '#B69FAF', category: 'Sb-xxxx-yy', building: 'Interest Point', positioning: '', special: 'Subway Station', construction: '', construction_eng: '', name: '地铁兴趣点', name_eng: 'Subway Station Interest Point'},
    'Sm-xxxx-yy': {letter: '', color: '#B69FAF', category: 'Sm-xxxx-yy', building: 'Interest Point', positioning: '', special: 'Stadium', construction: '', construction_eng: '', name: '体育馆兴趣点', name_eng: 'Stadium Interest Point'},
    'Ts-xxxx-yy': {letter: '', color: '#B69FAF', category: 'Ts-xxxx-yy', building: 'Interest Point', positioning: '', special: 'Tourist Sites', construction: '', construction_eng: '', name: '景区兴趣点', name_eng: 'Tourist Sites Interest Point'},
};

categoryMap['default'] = {letter: '', color: '', category: '', building: '', positioning: '', special: '', construction: '', construction_eng: '', name: '', name_eng: ''};

module.exports = {
    statusMap: {
        open: { name_eng: 'Open', name: '正常营业' },
        closed: { name_eng: 'Closed', name: '购物地点关闭' },
        remodelling: { name_eng: 'Remodelling', name: '购物地点装修中' },
        future: { name_eng: 'Future', name: '未开业的购物地点' }
    },
    subStatusMap: {
        future: {
            future_opening: { name_eng: 'Opening', name: '购物地点建设完成暂未开业' },
            future_12: { name_eng: 'Open Less Than 12 Month', name: '未来12月内计划开业' },
            future_12_24: { name_eng: 'Open Between 12 - 24 Month', name: '未来12~24个月计划开业' },
            future_25: { name_eng: 'Open More Than 24 Month', name: '未来24个月以后计划开业' },
            future_stopped: { name_eng: 'Seems Stopped', name: '开业计划暂停' },
            future_proposed: { name_eng: 'Proposed', name: '开业计划无法核定' },
            future_unknown: { name_eng: 'Unknown', name: '开业时间未知' }
        }
    },

    buildingMap: {
        'Mall': { name: '购物中心', name_eng: 'Mall', isHightPriority: true, categories: Object.keys(categoryMap).filter(key => categoryMap[key].building === 'Mall') },
        'Department Store': { name: '百货', name_eng: 'Department Store', isHightPriority: true, categories: Object.keys(categoryMap).filter(key => categoryMap[key].building === 'Department Store') },
        'Hypermarket': { name: '大卖场', name_eng: 'Hypermarket', isHightPriority: true, categories: Object.keys(categoryMap).filter(key => categoryMap[key].building === 'Hypermarket') },
        'Retail Building': { name: '商业大楼', name_eng: 'Retail Building', isHightPriority: true, categories: Object.keys(categoryMap).filter(key => categoryMap[key].building === 'Retail Building') },
        'Office Building': { name: '写字楼商业大楼', name_eng: 'Office Building', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].building === 'Office Building') },
        'Apartment Building': { name: '住宅商业大楼', name_eng: 'Apartment Building', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].building === 'Apartment Building') },
        'Hotel Building': { name: '酒店商业大楼', name_eng: 'Hotel Building', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].building === 'Hotel Building') },
        'Interest Point': { name: '兴趣点', name_eng: 'Interest Point', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].building === 'Interest Point') }
    },
    positioningMap: {
        'Luxury': { name: '奢华', name_eng: 'Luxury', categories: Object.keys(categoryMap).filter(key => categoryMap[key].positioning === 'Luxury') },
        'Premium': { name: '高端', name_eng: 'Premium', categories: Object.keys(categoryMap).filter(key => categoryMap[key].positioning === 'Premium') },
        'Brand': { name: '品牌', name_eng: 'Brand', categories: Object.keys(categoryMap).filter(key => categoryMap[key].positioning === 'Brand') },
        'Value': { name: '平价', name_eng: 'Value', categories: Object.keys(categoryMap).filter(key => categoryMap[key].positioning === 'Value') },
        'Local': { name: '个体', name_eng: 'Local', categories: Object.keys(categoryMap).filter(key => categoryMap[key].positioning === 'Local') }
    },
    specialMap: {
        'Fashion Boutique': { name: '精品服装', name_eng: 'Fashion Boutique', isHightPriority: true, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Fashion Boutique') },
        'Outlet': { name: '奥特莱斯', name_eng: 'Outlet', isHightPriority: true, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Outlet') },
        'Lifestyle': { name: '生活方式', name_eng: 'Lifestyle', isHightPriority: true, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Lifestyle') },
        'Entertainment': { name: '娱乐', name_eng: 'Entertainment', isHightPriority: true, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Entertainment') },
        'Market Boutique': { name: '精品集市', name_eng: 'Market Boutique', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Market Boutique') },
        'Food & Beverage': { name: '餐饮', name_eng: 'Food & Beverage', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Food & Beverage') },
        'Future': { name: '未来', name_eng: 'Future', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Future') },
        'Youth': { name: '青少年', name_eng: 'Youth', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Youth') },
        'Services': { name: '服务', name_eng: 'Services', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Services') },
        'Convenience': { name: '便捷', name_eng: 'Convenience', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Convenience') },
        'Furniture': { name: '家私', name_eng: 'Furniture', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Furniture') },
        'Children': { name: '婴童', name_eng: 'Children', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Children') },
        'Electronic': { name: '电子', name_eng: 'Electronic', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Electronic') },
        'Jewelry': { name: '珠宝', name_eng: 'Jewelry', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Jewelry') },
        'Gallery': { name: '单店', name_eng: 'Gallery', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Gallery') },
        'Individual Store': { name: '商户', name_eng: 'Individual Store', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Individual Store') },
        'Airport': { name: '机场', name_eng: 'Airport', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Airport') },
        'Train Station': { name: '火车站', name_eng: 'Train Station', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Train Station') },
        'Subway Station': { name: '地铁', name_eng: 'Subway Station', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Subway Station') },
        'Stadium': { name: '体育馆', name_eng: 'Stadium', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Stadium') },
        'Tourist Sites': { name: '景区', name_eng: 'Tourist Sites', isHightPriority: false, categories: Object.keys(categoryMap).filter(key => categoryMap[key].special === 'Tourist Sites') },
    },
    categoryMap: categoryMap,

};